apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
            - containerPort: 81  # expose stub_status
          volumeMounts:
            - name: nginx-status-conf
              mountPath: /etc/nginx/conf.d/stub_status.conf
              subPath: stub_status.conf
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.1.0
          args:
            - -nginx.scrape-uri=http://localhost:81/stub_status
          ports:
            - containerPort: 9113
      volumes:
        - name: nginx-status-conf
          configMap:
            name: nginx-status-conf
